notifications:
  commits: dev@felix.apache.org
  issues: dev@felix.apache.org
  pullrequests: dev@felix.apache.org
  jira_options: link label link label

publish:
  whoami: asf-site

#temporary
staging:
  profile: ~
  whoami:  asf-staging
