notifications:
  commits: dev@felix.apache.org
  issues: dev@felix.apache.org
  pullrequests: dev@felix.apache.org
  jira_options: link label link label

publish:
  whoami: asf-site

#temporary
staging:
  profile:
  whoami: asf-staging
github:
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
